config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :guarantees
  resources :searches

  match "/delayed_job" => DelayedJobWeb, :anchor => false, :via => [:get, :post]

  root 'guarantees#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guarantee.rb
class Guarantee < ApplicationRecord
  extend Enumerize

  #before_save :calculate_days

  auto_increment :correlative

  enumerize :bank_name, in: [:ESTADO, :SANTANDER, :BBVA, :CORPBANCA, :FALABELLA, :RIPLEY, :CHILE, :BICE, :SCOTIABANK, :CREDITO_E_INVERSIONES,
                            :EDWARDS, :INTERNACIONAL, :ITAU, :SECURITY, :PROAVAL, :HDI, :CONSORCIO, :FIRST_AVAL, :NOTARIA,
                            :MASAVAL, :BCI, :-]

  enumerize :state, in: [:DEVUELTA, :VENCIDA, :VIGENTE, :-], default: :VIGENTE

  enumerize :currency_guarantee, in: [:UF, :CLP, :EUR, :US, :-]

  enumerize :devolution_return, in: [:DESPACHO, :DESPACHO_CORRESPONDENCIA, :RETIRO_PERSONAL, :-]

  enumerize :guarantee_type, in: [:GARANTIA, :VALE_VISTA, :LETRA_CAMBIO, :CERTIFICADO_PRORROGA, :CERTIFICADO_FIANZA, :POLIZA_GARANTIA, :PAGARE, :CERTIFICADO]

  #def calculate_days
  #  if due_date.present?
  #    self.notification = (due_date - income_date).to_i
  #    self.notification = (notification - 30)
  #  end
  #end

end

app/models/search.rb
class Search < ApplicationRecord
  def search_guarantees

    guarantees = Guarantee.all

    guarantees = guarantees.where(["guarantee_type LIKE ?", "%#{keywords}%"]) if keywords.present?
    guarantees = guarantees.where(["guarantee_number LIKE ?", guarantee_number]) if guarantee_number.present?
    guarantees = guarantees.where(["borrower_name LIKE ?", borrower_name]) if borrower_name.present?
    guarantees = guarantees.where(["borrower_id LIKE ?", borrower_id]) if borrower_id.present?
    guarantees = guarantees.where(["value_guarantee LIKE ?", value_guarantee]) if value_guarantee.present?
    guarantees = guarantees.where(["detail LIKE ?", detail]) if detail.present?
    guarantees = guarantees.where(["sectorialist_devolution LIKE ?", sectorialist_devolution]) if sectorialist_devolution.present?


    return guarantees
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/guarantees_controller.rb
class GuaranteesController < ApplicationController
  before_action :set_guarantee, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [ :index ]

  # GET /guarantees
  # GET /guarantees.json
  def index
    @guarantees = Guarantee.all
    @excel = Guarantee.all

    respond_to do |format|
      format.html
      format.xlsx
    end
  end

  # GET /guarantees/1
  # GET /guarantees/1.json
  def show
  end

  # GET /guarantees/new
  def new
    @guarantee = Guarantee.new
  end

  # GET /guarantees/1/edit
  def edit
  end

  # POST /guarantees
  # POST /guarantees.json
  def create
    @guarantee = Guarantee.new(guarantee_params)

    respond_to do |format|
      if @guarantee.save
        format.html { redirect_to root_path, flash: { success: 'Registro creado correctamente'} }
        format.json { render :show, status: :created, location: @guarantee }
      else
        format.html { render :new }
        format.json { render json: @guarantee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guarantees/1
  # PATCH/PUT /guarantees/1.json
  def update
    respond_to do |format|
      if @guarantee.update(guarantee_params)
        #if @guarantee.due_date.present && @guarantee.income_date?
        #  SendEmailJob.set(wait: @guarantee.notification.days).perform_later(@guarantee)
        #end

        format.html { redirect_to root_path, flash: { success: 'Registro actualizado correctamente.'} }
        format.json { render :show, status: :ok, location: @guarantee }
      else
        format.html { render :edit }
        format.json { render json: @guarantee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guarantees/1
  # DELETE /guarantees/1.json
  def destroy
    @guarantee.destroy
    respond_to do |format|
      format.html { redirect_to guarantees_url, flash: { error: 'Registro eliminado.' } }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guarantee
      @guarantee = Guarantee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guarantee_params
      params.require(:guarantee).permit(:correlative, :income_number, :income_date, :income_applicant, :borrower_name, :borrower_id, :bank_name, :guarantee_type, :guarantee_number, :value_guarantee, :currency_guarantee, :due_date, :state, :bail, :detail, :bip, :devolution_number, :devolution_date, :devolution_return, :sectorialist_devolution, :email, :technical_unit, :observation, :notification)
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def new
    @search = Search.new
    #@guarantees = Guarantee.uniq.pluck(:guarantee_type)
  end

  def create
    @search = Search.create(search_params)
    redirect_to @search
  end

  def show
    @search = Search.find(params[:id])
  end

  private

  def search_params
    params.require(:search).permit(:keywords, :correlative, :income_number, :income_applicant, :borrower_name, :borrower_id, :bank_name, :guarantee_type, :guarantee_number, :value_guarantee, :currency_guarantee, :state, :bail, :detail, :bip, :devolution_number, :devolution_return, :sectorialist_devolution, :email, :technical_unit)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guarantees_helper.rb
module GuaranteesHelper
  def number_to_currency_clp(value_guarantee)
    number_to_currency(value_guarantee, :unit => "$ ", :separator => ".", :precision => 0)
  end

  def capitalize_name(income_applicant)
    income_applicant.gsub(/[A-Za-z']+/,&:capitalize)
  end

  def capitalize_detail(detail)
    detail.try(:capitalize)
  end

  def due_date_format(due_date)
    due_date.try(:strftime, "%d/%m/%Y")
  end

  def devolution_date_format(devolution_date)
    devolution_date.try(:strftime, "%d/%m/%Y")
  end

  def income_date_format(income_date)
    income_date.try(:strftime, "%d/%m/%Y")
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/assets/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <a class="navbar-brand" href="/">Sistema Boletas de Garantía</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <%= link_to 'Boletas', guarantees_path, class: "nav-link" %>
          <%= link_to current_user.email, edit_user_registration_path, class: "nav-link"  %>
          <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class: "nav-link" %>
        <% else %>
          <%= link_to 'Iniciar Sesión', new_user_session_path, class: "nav-link" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/guarantees/_form.html.erb
<%= simple_form_for(@guarantee) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-group">
    <div class="card">
      <h4 class="card-header">Datos de Ingreso</h4>
      <div class="card-body">
        <%= f.input :guarantee_type, label: "Tipo Garantia", include_blank: false %>
        <%= f.input :income_number, label: "Numero de Ingreso" %>
        <%= f.input :income_applicant, label: "Solicitante de Ingreso" %>
        <%= f.input :income_date, as: :string, label: "Fecha de Ingreso", input_html: { class: 'datepicker0' } %>
      </div>
    </div>
    <br>
    <div class="card">
      <h4 class="card-header">Datos Prestador</h4>
      <div class="card-body">
        <%= f.input :borrower_name, label: "Nombre Tomador" %>
        <%= f.input :borrower_id, label: "ID Tomador", as: :string %>
      </div>
    </div>
    <br>
    <div class="card">
      <h4 class="card-header">Bancos</h4>
      <div class="card-body">
        <%= f.input :bank_name, label: "Nombre Banco" %>
      </div>
    </div>
    <br>
    <div class="card">
      <h4 class="card-header">Detalles de la Garantía</h4>
      <div class="card-body">
        <%= f.input :guarantee_number, label: "Numero de Garantía" %>
        <%= f.input :value_guarantee, label: "Valor Garantia", as: :string %>
        <%= f.input :currency_guarantee, label: "Moneda Garantía" %>
        <% if @guarantee.guarantee_type === 'VALE_VISTA' %>
          <%= f.input :due_date, as: :string, label: "Fecha de Vencimiento", disabled:true, input_html: { class: 'datepicker1' } %>
        <% else %>
          <%= f.input :due_date, as: :string, label: "Fecha de Vencimiento", input_html: { class: 'datepicker1' } %>
        <% end %>
        <%= f.input :bail, label: "Caución" %>
        <%= f.input :detail, label: "Detalle" %>
        <%= f.input :bip, label: "Codigo BIP" %>
        <%= f.input :email, label: "Correo Electronico" %>
        <%= f.input :observation, label: "Observación", input_html: { rows: 2 } %>
      </div>
      <div class="card-footer">
        <div class="form-actions">
          <%= f.button :submit, class: 'btn btn-primary' %>
          <%= link_to 'Cancelar', root_path, class: 'btn btn-secondary' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/guarantees/_second_form.html.erb
<%= simple_form_for(@guarantee) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-group">
    <div class="card">
      <h4 class="card-header">Datos Devolución</h4>
      <div class="card-body">
        <%= f.input :correlative, label: "Correlativo", disabled: true %>
        <%= f.input :state, label: "Estado boleta" %>
        <%= f.input :devolution_number, label: "Numero de Devolución" %>
        <%= f.input :devolution_date, as: :string, label: "Fecha de Devolución", input_html: { class: 'datepicker2' }, format: :chile %>
        <%= f.input :devolution_return, label: "Medio de Devolución" %>
        <%= f.input :sectorialist_devolution, label: "Sectorialista Devolución" %>
        <%= f.input :technical_unit, label: "Unidad Tecnica" %>
        <%= f.input :email, label: "Correo Electronico" %>
        <%= f.input :observation, label: "Observación", input_html: { rows: '2' } %>
      </div>
    </div>
    <br>
    <div class="card">
      <h4 class="card-header">Datos de Ingreso</h4>
      <div class="card-body">
        <%= f.input :guarantee_type, label: "Tipo Garantia", include_blank: false %>
        <%= f.input :income_number, label: "Numero de Ingreso" %>
        <%= f.input :income_applicant, label: "Solicitante de Ingreso" %>
        <%= f.input :income_date, as: :string, label: "Fecha de Ingreso", input_html: { class: 'datepicker0' } %>
      </div>
    </div>
    <br>
    <div class="card">
      <h4 class="card-header">Datos Prestador</h4>
      <div class="card-body">
        <%= f.input :borrower_name, label: "Nombre Tomador" %>
        <%= f.input :borrower_id, label: "ID Tomador", as: :string %>
      </div>
    </div>
    <br>
    <div class="card">
      <h4 class="card-header">Bancos</h4>
      <div class="card-body">
        <%= f.input :bank_name, label: "Nombre Banco" %>
      </div>
    </div>
    <br>
    <div class="card">
      <h4 class="card-header">Detalles de la Garantía</h4>
      <div class="card-body">
        <%= f.input :guarantee_number, label: "Numero de Garantía" %>
        <%= f.input :value_guarantee, label: "Valor Garantia", as: :string %>
        <%= f.input :currency_guarantee, label: "Moneda Garantía" %>
        <% if @guarantee.guarantee_type === 'VALE_VISTA' %>
          <%= f.input :due_date, as: :string, label: "Fecha de Vencimiento", disabled:true, input_html: { class: 'datepicker1' } %>
        <% else %>
          <%= f.input :due_date, as: :string, label: "Fecha de Vencimiento", input_html: { class: 'datepicker1' } %>
        <% end %>
        <%= f.input :bail, label: "Caución" %>
        <%= f.input :detail, label: "Detalle" %>
        <%= f.input :bip, label: "Codigo BIP" %>
        <%= f.input :observation, label: "Observación", input_html: { rows: 2 } %>
      </div>
      <div class="card-footer">
        <div class="form-actions">
          <%= f.button :submit, class: 'btn btn-primary' %>
          <%= link_to 'Cancelar', root_path, class: 'btn btn-secondary' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/guarantees/edit.html.erb
<%= render 'second_form', guarantee: @guarantee %>

app/views/guarantees/index.html.erb
<p id="notice">
  <%= notice %>
</p>

<div class="row">
  <div class="col-md-6">
    <h3>Sistema Boletas de Garantía</h3>
  </div>
  <% if user_signed_in? %>
    <div class="col-md-6">
      <p class="text-right">
        <%= link_to 'Agregar Nuevo Registro', new_guarantee_path, class: 'btn btn-primary'  %>
        <%= link_to 'Busqueda Avanzada', new_search_path, class: 'btn btn-primary' %>
        <%= link_to guarantees_path(format: "xlsx"), class: 'btn btn-success' do %>
          <% icon('far', 'file-excel') %>
        <% end %>
      </p>
    </div>
  <% end %>
</div>
<hr>
<div class="table-responsive-xl">
  <table class="table table-striped text-center" id="dttb">
    <thead>
      <tr>
        <th>Correlativo</th>
        <th>Numero Boleta</th>
        <th>Proveedor</th>
        <th>Analista</th>
        <th>Detalle</th>
        <th>Estado</th>
        <% if user_signed_in? %>
          <th>Acciones</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @guarantees.each do |guarantee| %>
        <tr>
          <% if guarantee.correlative.present? %>
            <td><%= guarantee.correlative %></td>
          <% else %>
            <td>SIN CORRELATIVO DEFINIDO</td>
          <% end %>
          <% if guarantee.guarantee_number.present? %>
            <td><%= guarantee.guarantee_number %></td>
          <% else %>
            <td>SIN NUMERO DEFINIDO</td>
          <% end %>
          <% if guarantee.guarantee_number.present? %>
            <td><%= guarantee.borrower_name %></td>
          <% else %>
            <td>SIN PROVEEDOR DEFINIDO</td>
          <% end %>
          <% if guarantee.income_applicant.present? %>
            <td><%= guarantee.income_applicant %></td>
          <% else %>
            <td>SIN ANALISTA DEFINIDO</td>
          <% end %>
          <% if guarantee.detail.present? %>
            <td><%= guarantee.detail %></td>
          <% else %>
            <td>SIN DETALLE DEFINIDO</td>
          <% end %>
          <% if guarantee.state.present? %>
            <td><%= guarantee.state %></td>
          <% else %>
            <td>SIN ESTADO DEFINIDO</td>
          <% end %>
          <% if user_signed_in? %>
            <td>
              <%= link_to guarantee_path(guarantee), class: 'btn btn-primary' do %>
                <% icon('fas', 'print') %>
              <% end %>
              <%= link_to edit_guarantee_path(guarantee), class: 'btn btn-success' do %>
                <% icon('fas', 'edit') %>
              <% end %>
              <%= link_to guarantee, method: :delete, data: { confirm: 'Esta seguro?' }, class: 'btn btn-danger' do %>
                <% icon('fas', 'trash-alt') %>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/guarantees/new.html.erb
<h4>Ingresar Nueva Boleta de Garantía</h4>
<hr>
<%= render 'form', guarantee: @guarantee %>

app/views/guarantees/show.html.erb
<style type="text/css">
  @media print {
    nav {
      display: none;
    }
    body {
      background-color:#FFFFFF;
      background-image:none;
      color:#000000;
    }
    #ad {
      display:none;
    }
    #leftbar {
      display:none;
    }
    #contentarea {
      padding-top: 70px;
      width:100%;
      padding-left: 100px;
    }
    .btn {
      display: none;
    }
  }
</style>
<div id="contentarea">
  <div style="width: 216mm; height: 279mm;">
    <div style="border: 0px solid black;  margin-right: 3px; margin-left: 3px;">
      <h1 style="text-align: center;">REGISTRO DE GARANTIA N°: <%= @guarantee.correlative %> </h1>
      <br>
      <table border="0" cellpadding="1" cellspacing="1">
        <tbody>
          <tr>
            <td style="width: 150px;"><span style="font-weight: bold;">CONTRATISTA</span></td>
            <td style="border-bottom-width: 1px; width: 600px;"><%= @guarantee.borrower_name %></td>
          </tr>
          <tr>
            <td><span style="font-weight: bold;">PROYECTO</span></td>
            <td style="border-bottom-width: 1px; width: 600px"><%= @guarantee.detail %></td>
          </tr>
          <tr>
            <td><span style="font-weight: bold;">SECTORIALISTA</span></td>
            <td style="border-bottom-width: 1px;"><%= @guarantee.income_applicant %></td>
          </tr>
        </tbody>
      </table>
      <br>
      <br>
      <br>
      <table style="text-align: left;" border="0" cellpadding="1" cellspacing="1">
        <tbody>
          <tr>
            <td style="width: 250px;" </td>
            <td style="font-weight: bold; text-align: left;" colspan="2" ><span style="text-decoration: underline;">BOLETA DEVUELTA</span></td>
          </tr>
          <tr>
            <td></td>
            <td style="font-weight: bold; width: 126px;" >BOLETA N&deg;</td>
            <td style="border-bottom-width: 1px; width: 366px;" ><%= @guarantee.guarantee_number %></td>
          </tr>
          <tr>
            <td></td>
            <td style="font-weight: bold; width: 126px;">BANCO</td>
            <td style="border-bottom-width: 1px; width: 366px;"><%= @guarantee.bank_name %></td>
          </tr>
          <tr>
            <td></td>
            <td style="font-weight: bold; width: 126px;">MONTO $</td>
            <td style="border-bottom-width: 1px; width: 366px;"><%= @guarantee.value_guarantee %> <%= @guarantee.currency_guarantee %></td>
          </tr>
          <tr>
            <td></td>
            <td style="font-weight: bold; width: 126px;"><br><br><br>V&deg;B&deg;</td>
            <td style="border-bottom-width: 1px; width: 366px;"></td>
          </tr>
        </tbody>
      </table>
      <br>
      <br>
      <table style="text-align: left; " border="0" cellpadding="2" cellspacing="2">
    <tbody>
      <tr style="font-weight: bold; text-decoration: underline;">
        <td colspan="4">INGRESO GARANTIA A TESORERIA</td>
      </tr>
      <tr>
        <td>DOCUMENTO N&deg;:</td>
        <td style="border-bottom-width: 1px; width: 230px;"><%= @guarantee.income_number %></td>
        <td>FECHA:</td>
        <td style="border-bottom-width: 1px; width: 230px;"><%= @guarantee.income_date %></td>
      </tr>
    </tbody>
  </table>
  <br>
  <br>
  <% if @guarantee.guarantee_type != 'VALE_VISTA' %>
    <table style="text-align: left;" border="0" cellpadding="2" cellspacing="2">
      <tbody>
        <tr style="font-weight: bold; text-decoration: underline;">
          <td colspan="4">DEVOLUCION DE GARANTIA</td>
        </tr>
        <tr>
          <td>DOCUMENTO N&deg;:</td>
          <td style="border-bottom-width: 1px; width: 230px;"><%= @guarantee.income_number %></td>
          <td>FFECHA:</td>
          <% if @guarantee.devolution_date? %>
            <td style="border-bottom-width: 1px; width: 230px;"><%= @guarantee.devolution_date %></td>
          <% else %>
            <td style="border-bottom-width: 1px; width: 230px;">-</td>
          <% end %>
        </tr>
        <tr>
          <td>SOLICITADOR POR:</td>
          <td style="border-bottom-width: 1px; width: 230px;" colspan="3"><%= @guarantee.sectorialist_devolution %></td>
        </tr>
        <tr>
          <td>MEDIO DEVOLUCION:</td>
          <td style="border-bottom-width: 1px; width: 230px;" colspan="3"><%= @guarantee.devolution_return %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
  <br>
  <br>
  <a class="btn btn-primary" href="#" onclick="window.print();return false;">Imprimir</a>
  <%= link_to 'Cancelar', root_path, class: 'btn btn-light' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gobierno Regional de Los Ríos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% unless flash.empty? %>
      <script type="text/javascript">
          <% flash.each do |f| %>
          <% type = f[0].to_s %>
          toastr['<%= type %>']('<%= f[1] %>');
          <% end %>
      </script>
    <% end %>

    <%= render 'assets/nav' %>
    <br>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/searches/new.html.erb
<h4>Busqueda Avanzada</h4>
<p>Ingrese uno de los siguientes campos para realizar la busqueda avanzada.</p>
<hr>
<%= simple_form_for(@search) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="card">
    <div class="card-body">
      <div class="row">
        <div class="col-md-12">
          <%= f.input :guarantee_number, label: "Numero Boleta de Garantia" %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6">
          <%= f.input :borrower_id, label: 'RUT Proveedor' %>
        </div>
        <div class="col-md-6">
          <%= f.input :borrower_name, label: 'Nombre Proveedor' %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <%= f.input :value_guarantee, label: 'Valor Boleta' %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <%= f.input :sectorialist_devolution, label: 'Analista' %>
        </div>
      </div>
    </div>
    <div class="card-footer">
      <div class="form-actions">
        <%= f.button :submit, class: 'btn btn-primary' %>
        <%= link_to 'Cancelar', root_path, class: 'btn btn-light' %>
      </div>
    </div>
  </div>


<% end %>

app/views/searches/show.html.erb
<h1>Resultado de Busqueda</h1>
<hr>
<% if @search.search_guarantees.empty? %>
  <p>Sin Registros</p>
<% else %>
  <% @search.search_guarantees.each do |c| %>
    <div class="card">
      <h4 class="card-header">
        <%= c.detail %>
      </h4>
      <div class="card-body">
        <h4>Datos Boleta</h4>
        <hr>
        <div class="row">
          <div class="col-md-4">
            <p>Numero Correlativo: <%= c.correlative %></p>
          </div>
          <div class="col-md-4">
            <p>Numero Ingreso: <%= c.income_number %></p>
          </div>
          <div class="col-md-4">
            <p>Fecha Ingreso: <%= c.income_date %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4">
            <p>Nombre Proveedor: <%= c.borrower_name %></p>
          </div>
          <div class="col-md-4">
            <p>RUT Proveedor: <%= c.borrower_id %></p>
          </div>
          <div class="col-md-4">
            <p>Banco: <%= c.bank_name %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4">
            <p>Numero Boleta: <%= c.guarantee_number %></p>
          </div>
          <div class="col-md-4">
            <p>Tipo Boleta: <%= c.guarantee_type %></p>
          </div>
          <div class="col-md-4">
            <p>Valor Boleta: <%= c.value_guarantee %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4">
            <p>Moneda: <%= c.currency_guarantee %></p>
          </div>
          <div class="col-md-4">
            <p>Fecha Vencimiento: <%= c.due_date %></p>
          </div>
          <div class="col-md-4">
            <p>Estado: <%= c.state %></p>
          </div>
        </div>
      </div>
    </div>
    <br>
  <% end %>
<% end %>